export default {
  isLoggedIn: false,
  name: '',
  role: '',
  title: `Thông Tin Tài Khoản Đăng Nhập`,
  isLoading: false,
  isModalOpened: false,
  editingRec: {},
  backupRec: {},
  selected: [],
  recs: [],
  icon: 'security',
  cols: [
    {
      name: 'edit',
      align: 'left',
      field: 'edit',
      width: '34px',
    },
    {
      name: 'username',
      label: 'Tên Đăng Nhập',
      align: 'left',
      field: 'username',
      sortable: true,
    },
    {
      name: 'password',
      label: 'Mật Khẩu',
      align: 'left',
      field: 'password',
    },
    {
      name: 'roles',
      label: 'Phân Quyền',
      align: 'left',
      field: 'roles',
      sortable: true,
    },
    {
      name: 'createdAt',
      label: 'Ngày Khởi Tạo',
      align: 'left',
      field: 'createdAt',
      sortable: true,
    },
  ],
  fields: [
    {
      name: 'id',
      hidden: true,
    },
    {
      name: 'username',
      label: 'Tên Đăng Nhập',
      type: 'text',
      icon: 'face',
    },
    {
      name: 'password',
      label: 'Mật Khẩu',
      type: 'text',
      icon: 'vpn_key',
    },
    {
      name: 'roles',
      label: 'Phân Quyền',
      type: 'text',
      icon: 'supervised_user_circle',
    },
  ],
}
